// Code generated from hl7.fhir.r4.core 4.0.1 CompartmentDefinition/patient; DO NOT EDIT.

package engine

// patientBindingPaths lists, for every FHIR R4 resource type, the element
// paths that bind a resource to its patient: the paths of the type's
// `patient` search parameter or, for a Patient-compartment type without one,
// of its compartment parameters. A type with no paths is outside the
// Patient compartment. A path may also name non-Patient references.
var patientBindingPaths = map[string][]string{
	"Account":                           {"subject"},
	"ActivityDefinition":                nil,
	"AdverseEvent":                      {"subject"},
	"AllergyIntolerance":                {"patient"},
	"Appointment":                       {"participant.actor"},
	"AppointmentResponse":               {"actor"},
	"AuditEvent":                        {"agent.who", "entity.what"},
	"Basic":                             {"subject"},
	"Binary":                            nil,
	"BiologicallyDerivedProduct":        nil,
	"BodyStructure":                     {"patient"},
	"Bundle":                            nil,
	"CapabilityStatement":               nil,
	"CarePlan":                          {"subject"},
	"CareTeam":                          {"subject"},
	"CatalogEntry":                      nil,
	"ChargeItem":                        {"subject"},
	"ChargeItemDefinition":              nil,
	"Claim":                             {"patient"},
	"ClaimResponse":                     {"patient"},
	"ClinicalImpression":                {"subject"},
	"CodeSystem":                        nil,
	"Communication":                     {"subject"},
	"CommunicationRequest":              {"subject"},
	"CompartmentDefinition":             nil,
	"Composition":                       {"subject"},
	"ConceptMap":                        nil,
	"Condition":                         {"subject"},
	"Consent":                           {"patient"},
	"Contract":                          nil,
	"Coverage":                          {"beneficiary"},
	"CoverageEligibilityRequest":        {"patient"},
	"CoverageEligibilityResponse":       {"patient"},
	"DetectedIssue":                     {"patient"},
	"Device":                            nil,
	"DeviceDefinition":                  nil,
	"DeviceMetric":                      nil,
	"DeviceRequest":                     {"subject"},
	"DeviceUseStatement":                {"subject"},
	"DiagnosticReport":                  {"subject"},
	"DocumentManifest":                  {"subject"},
	"DocumentReference":                 {"subject"},
	"EffectEvidenceSynthesis":           nil,
	"Encounter":                         {"subject"},
	"Endpoint":                          nil,
	"EnrollmentRequest":                 {"candidate"},
	"EnrollmentResponse":                nil,
	"EpisodeOfCare":                     {"patient"},
	"EventDefinition":                   nil,
	"Evidence":                          nil,
	"EvidenceVariable":                  nil,
	"ExampleScenario":                   nil,
	"ExplanationOfBenefit":              {"patient"},
	"FamilyMemberHistory":               {"patient"},
	"Flag":                              {"subject"},
	"Goal":                              {"subject"},
	"GraphDefinition":                   nil,
	"Group":                             {"member.entity"},
	"GuidanceResponse":                  nil,
	"HealthcareService":                 nil,
	"ImagingStudy":                      {"subject"},
	"Immunization":                      {"patient"},
	"ImmunizationEvaluation":            {"patient"},
	"ImmunizationRecommendation":        {"patient"},
	"ImplementationGuide":               nil,
	"InsurancePlan":                     nil,
	"Invoice":                           {"subject"},
	"Library":                           nil,
	"Linkage":                           nil,
	"List":                              {"subject"},
	"Location":                          nil,
	"Measure":                           nil,
	"MeasureReport":                     {"subject"},
	"Media":                             {"subject"},
	"Medication":                        nil,
	"MedicationAdministration":          {"subject"},
	"MedicationDispense":                {"subject"},
	"MedicationKnowledge":               nil,
	"MedicationRequest":                 {"subject"},
	"MedicationStatement":               {"subject"},
	"MedicinalProduct":                  nil,
	"MedicinalProductAuthorization":     nil,
	"MedicinalProductContraindication":  nil,
	"MedicinalProductIndication":        nil,
	"MedicinalProductIngredient":        nil,
	"MedicinalProductInteraction":       nil,
	"MedicinalProductManufactured":      nil,
	"MedicinalProductPackaged":          nil,
	"MedicinalProductPharmaceutical":    nil,
	"MedicinalProductUndesirableEffect": nil,
	"MessageDefinition":                 nil,
	"MessageHeader":                     nil,
	"MolecularSequence":                 {"patient"},
	"NamingSystem":                      nil,
	"NutritionOrder":                    {"patient"},
	"Observation":                       {"subject"},
	"ObservationDefinition":             nil,
	"OperationDefinition":               nil,
	"OperationOutcome":                  nil,
	"Organization":                      nil,
	"OrganizationAffiliation":           nil,
	"Patient":                           {"link.other"},
	"PaymentNotice":                     nil,
	"PaymentReconciliation":             nil,
	"Person":                            {"link.target"},
	"PlanDefinition":                    nil,
	"Practitioner":                      nil,
	"PractitionerRole":                  nil,
	"Procedure":                         {"subject"},
	"Provenance":                        {"target"},
	"Questionnaire":                     nil,
	"QuestionnaireResponse":             {"subject"},
	"RelatedPerson":                     {"patient"},
	"RequestGroup":                      {"subject"},
	"ResearchDefinition":                nil,
	"ResearchElementDefinition":         nil,
	"ResearchStudy":                     nil,
	"ResearchSubject":                   {"individual"},
	"RiskAssessment":                    {"subject"},
	"RiskEvidenceSynthesis":             nil,
	"Schedule":                          {"actor"},
	"SearchParameter":                   nil,
	"ServiceRequest":                    {"subject"},
	"Slot":                              nil,
	"Specimen":                          {"subject"},
	"SpecimenDefinition":                nil,
	"StructureDefinition":               nil,
	"StructureMap":                      nil,
	"Subscription":                      nil,
	"Substance":                         nil,
	"SubstanceNucleicAcid":              nil,
	"SubstancePolymer":                  nil,
	"SubstanceProtein":                  nil,
	"SubstanceReferenceInformation":     nil,
	"SubstanceSourceMaterial":           nil,
	"SubstanceSpecification":            nil,
	"SupplyDelivery":                    {"patient"},
	"SupplyRequest":                     {"deliverTo"},
	"Task":                              nil,
	"TerminologyCapabilities":           nil,
	"TestReport":                        nil,
	"TestScript":                        nil,
	"ValueSet":                          nil,
	"VerificationResult":                nil,
	"VisionPrescription":                {"patient"},
}

// dateSearchPaths names, for the resource types a record request may name,
// the element path of the type's `date` search parameter.
var dateSearchPaths = map[string]string{
	"DiagnosticReport":  "effective",
	"DocumentReference": "date",
}
